### ISSUE TITLE
Bug to fix for bounty in nov13

### ISSUE THREAD

**Issue by anna04test** [Org4/nov13#1]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0xa17def85426f8e9cb6e3bfa2dc90df30f2a1446c35410e80d8ef06bc16242bdf](https://ropsten.etherscan.io/tx/0xa17def85426f8e9cb6e3bfa2dc90df30f2a1446c35410e80d8ef06bc16242bdf)
