### ISSUE TITLE
two

### ISSUE THREAD

**Issue by anna04test** [Org4/nov13#3]

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im:444/img/deploying_contract.png)
Transaction: [0x5d486d2df36212c6591d7f3cce59f1af49eec0d3a3d4691e5764c5ef442bfe0f](https://ropsten.etherscan.io/tx/0x5d486d2df36212c6591d7f3cce59f1af49eec0d3a3d4691e5764c5ef442bfe0f)
