### ISSUE TITLE
red issue

### ISSUE THREAD

**Issue by anna04test** [Org4/nov13#5]
R

**Comment by status-open-bounty** [comment]
Balance: 0.000008 ETH
Contract address: [0xb0d566ea8c4d7d0cbd0f1e6cef41a1d159af09e1](https://ropsten.etherscan.io/address/0xb0d566ea8c4d7d0cbd0f1e6cef41a1d159af09e1)
Network: Testnet (Ropsten)
Paid to: annadanchenko
